Write an algorithm such that if an element in an M*N matrix is 0, its entire row and column are set to 0.

In [1]:
import numpy as np


In [79]:
def matrix(m,n):
    l=[]
    x=np.ones((m,n))
    x[0,0]=0
    x[5,3]=0
    print(x)
    for i in range(0,m):
        for j in range(0,n):
            if x[i][j]==0:
                l.append((i,j))
    print(l)
    for each in l:
        x[each[0],:]=0
        x[:,each[1]]=0
    print(x)
    
    
matrix(6,6)

[[0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1.]]
[(0, 0), (5, 3)]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0.]]
